services:
  marending-dev:
    image: "ghcr.io/beingflo/marending-dev:0.2.23"
    container_name: marending.dev
    env_file: ".env.prod"
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - caddy_net
      - events_net

networks:
  caddy_net:
    external: true
  events_net:
    external: true
