services:
  marending-dev:
    image: "ghcr.io/beingflo/marending-dev:latest"
    container_name: marending.dev
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
