export const notes = {
	'responsive-plots': {
		title: 'Responsive plots in SolidJS',
		subtitle: 'Saving you very little trouble',
		date: '21 Apr 2025',
		link: '/notes/responsive-plots/',
		draft: false,
	},
	go: {
		title: 'go: An opinionated bookmark aggregator',
		subtitle: 'A project report',
		date: '23 Dec 2024',
		link: '/notes/go-rest-quest/',
		draft: true,
	},
	'co2-loft': {
		title: 'The air quality impact of living in a loft apartment',
		subtitle: 'Now without doors',
		date: '10 Nov 2024',
		link: '/notes/co2-loft/',
		draft: false,
	},
	'sqlite-vs-duckdb': {
		title: 'SQLite and DuckDB for analytics workload',
		subtitle: 'The impact of column orientation',
		date: '15 Sep 2024',
		link: '/notes/sqlite-vs-duckdb/',
		draft: false,
	},
	'unstructured-data': {
		title: 'How to store and query unstructured data',
		subtitle: 'Reinventing the wheel',
		date: '12 Sep 2024',
		link: '/notes/unstructured-data/',
		draft: false,
	},
	'rest-quest': {
		title: 'rest.quest: An opinionated to-do list',
		subtitle: 'A project report',
		date: '17 Aug 2024',
		link: '/notes/rest-quest/',
		draft: false,
	},
	fieldnotes: {
		title: 'Fieldnotes: An end-to-end encrypted note-taking application',
		subtitle: 'A project report',
		date: '28 Apr 2024',
		link: '/notes/fieldnotes/',
		draft: false,
	},
	'rust-spa': {
		title: 'How to host single-page applications',
		subtitle: 'Web server vs. application server',
		date: '03 Mar 2024',
		link: '/notes/rust-spa/',
		draft: false,
	},
	'16-hour-projects': {
		title: '16 hour side-projects',
		subtitle: 'An ode to the MVP',
		date: '29 Feb 2024',
		link: '/notes/16-hour-projects/',
		draft: false,
	},
	'wasm-benchmark': {
		title: 'Native Rust vs Webassembly performance microbenchmark',
		subtitle: "You won't believe the outcome",
		date: '02 Jan 2024',
		link: '/notes/wasm-benchmark/',
		draft: false,
	},
	'vps-benchmarks': {
		title: 'A brief comparison of Hetzner servers',
		subtitle: 'ARM is a viable option',
		date: '01 Jan 2024',
		link: '/notes/vps-benchmarks/',
		draft: false,
	},
	'sqlite-benchmarks': {
		title: 'How fast is SQLite?',
		subtitle: 'Plenty fast',
		date: '31 Dec 2023',
		link: '/notes/sqlite-benchmarks/',
		draft: false,
	},
	'league-rating': {
		title: 'Analyzing rating systems for foosball outcomes',
		subtitle: 'Color me disappointed',
		date: '02 Sep 2023',
		link: '/notes/league-rating/',
		draft: false,
	},
	'league-data': {
		title: '9 years worth of company foosball data analyzed',
		subtitle: 'Nobody tell management',
		date: '13 Jul 2023',
		link: '/notes/league-data/',
		draft: false,
	},
	'co2-bedroom': {
		title: 'The air quality impact of closing your bedroom door at night',
		subtitle: 'Trying not to suffocate while sleeping',
		date: '10 May 2023',
		link: '/notes/co2-bedroom/',
		draft: false,
	},
	'esp-protocol': {
		title: 'A comparison of wireless protocols for battery powered embedded devices',
		subtitle: 'Trying to sleep as much as possible',
		date: '17 Apr 2023',
		link: '/notes/esp-protocol/',
		draft: false,
	},
	'esp-power': {
		title: 'Measuring power consumption of ESP32 development boards',
		subtitle: 'First forays into embedded devices',
		date: '25 Feb 2023',
		link: '/notes/esp-power/',
		draft: false,
	},
	performance: {
		title: 'Performance tuning a specific SvelteKit application',
		subtitle: `Making sure my website can handle all those page views it isn't getting`,
		date: '29 Dec 2022',
		link: '/notes/performance/',
		draft: false,
	},
	lines: {
		title: 'A study of lines',
		subtitle: 'Some schmuck tries his hands at generative art',
		date: '03 Dec 2022',
		link: '/notes/lines/',
		draft: false,
	},
	website: {
		title: 'About this website',
		subtitle: 'There are many like it, but this one is mine',
		date: '27 Nov 2022',
		link: '/notes/website/',
		draft: false,
	},
};
