name: Build

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
        working-directory: ./ui
      - run: npm run build
        working-directory: ./ui
      - name: Deploy to prod server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OMNI_GH_KEY }}
          SOURCE: "ui/dist/"
          REMOTE_HOST: ${{ secrets.OMNI_HOST }}
          REMOTE_USER: ${{ secrets.OMNI_USER }}
          TARGET: "~/caddy/site/marending.dev/"
